server:
  port: 8080

spring:
  application:
    name: Music-player
  datasource:
    url: jdbc:h2:mem:musicdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

